variable "technitium_url" {
  type        = string
  description = "Technitium API URL, e.g. https://ns1.<lan_domain> - NO TRAILING SLASH (the provider concatenates this directly with /api/... paths; a trailing slash produces a double-slash path that 404s with an empty body, which surfaces as a confusing \"cannot decode JSON response: EOF\" rather than a clear error). Any cluster member works, clustering (via the shared catalog zone) replicates changes to the others. No default - supply via a gitignored local.auto.tfvars (see local.auto.tfvars.example)."
}

variable "technitium_token" {
  type        = string
  sensitive   = true
  description = "Technitium API token, created out-of-band via the admin UI (same pattern as every other credential in this pipeline - never generated by Terraform). No default - supply via a gitignored local.auto.tfvars (see local.auto.tfvars.example)."
}

variable "record_ttl" {
  type        = number
  default     = 3600
  description = "TTL (seconds) applied to every record this module manages - technitium_record has no default of its own, ttl is a required attribute."
}
