output "mon_hosts" {
  description = "Ceph mon addresses - for consumers (tf-pve-docker-swarm, and eventually the Ansible mount step) to reach the cluster"
  value       = var.mon_hosts
}

output "fs_name" {
  description = "The CephFS filesystem name actually deployed by this module (reflects whichever identity was applied - e.g. \"cephfs-test\" or \"cephfs\")"
  value       = var.fs_name
}

output "fsid" {
  description = "Ceph cluster fsid"
  value       = var.fsid
}

# No client key output, deliberately - the client.swarm auth key is created
# out-of-band (same pattern as every other secret in this pipeline: PVE API
# tokens, MinIO credentials) and only ever referenced via a variable elsewhere,
# never generated by or read back through Terraform state.
