---
- name: Deploy Traefik
  hosts: bootstrap

  tasks:
    - name: Copy traefik dir
      ansible.posix.synchronize:
        src: .
        dest: .

    - name: Create hashed password
      ansible.builtin.command: openssl passwd -apr1 {{ traefik_password }}
      changed_when: false
      register: hashed_password_raw

    - name: Save hashed password
      ansible.builtin.set_fact:
        hashed_password: '{{ hashed_password_raw.stdout_lines[0] }}'

    - name: Add traefik label for the certificate-volume node
      ansible.builtin.command: docker node update --label-add traefik-public.traefik-public-certificates=true {{ inventory_hostname }}
      changed_when: true

    - name: Create traefik network
      ansible.builtin.shell: docker network create --driver=overlay traefik-public > create_traefik_network.txt
      args:
        chdir: $HOME
        creates: create_traefik_network.txt

    - name: Deploy traefik
      ansible.builtin.command: docker stack deploy -c traefik/docker-compose.yml traefik
      environment:
        USERNAME: '{{ traefik_username }}'
        HASHED_PASSWORD: '{{ hashed_password }}'
        EMAIL: '{{ traefik_email }}'
        DOMAIN: '{{ traefik_domain }}'
      args:
        chdir: $HOME
      changed_when: true
