variable "technitium_url" {
  type        = string
  description = "Technitium API URL, e.g. https://ns1.<lan_domain> - NO TRAILING SLASH (see tf-dns-technitium/variables.tf for why). No default - supply via a gitignored local.auto.tfvars (see local.auto.tfvars.example)."
}

variable "technitium_token" {
  type        = string
  sensitive   = true
  description = "Technitium API token, created out-of-band via the admin UI (same pattern as every other credential in this pipeline - never generated by Terraform). No default - supply via a gitignored local.auto.tfvars (see local.auto.tfvars.example)."
}

variable "record_ttl" {
  type        = number
  default     = 3600
  description = "TTL (seconds) for the secrets host A record."
}

# The LXC itself is out of scope for this module - it's a manually-created
# (Proxmox community-scripts) container, not Terraform-provisioned, unlike
# every VM elsewhere in this pipeline. This module only formalizes its DNS
# record under IaC, matching how every other record in this project is
# Terraform-managed regardless of how the underlying host was provisioned.
variable "secrets_domain" {
  type        = string
  description = "Domain for the key-infra secrets host, e.g. secrets.lan.bauer.com.au. No default - supply via a gitignored local.auto.tfvars (see local.auto.tfvars.example)."
}

variable "secrets_ipaddr" {
  type        = string
  description = "IP address of the manually-provisioned secrets LXC. No default - supply via a gitignored local.auto.tfvars (see local.auto.tfvars.example)."
}
